//! Phase 10: HTML reporter.
//!
//! Renders a `ScanReport` to a self-contained HTML document — inline CSS,
//! no external CDNs, no JavaScript. The output is the canonical artifact
//! for both the `--output html` mode and the PDF reporter (which lifts
//! data out of the same `ScanReport` directly).

use std::fmt::Write;

use crate::models::finding::{CertFinding, HttpFinding, Recommendation, TlsFinding, Vulnerability};
use crate::models::report::ScanReport;
use crate::models::risk::RiskLevel;

pub struct HtmlReporter;

impl HtmlReporter {
    pub fn render(report: &ScanReport) -> String {
        let mut out = String::with_capacity(8 * 1024);
        write_doc(&mut out, report);
        out
    }
}

fn write_doc(buf: &mut String, report: &ScanReport) {
    let color = report.risk_score.level.color_code();
    let level = report.risk_score.level.label();
    // An unreachable scan has no meaningful numeric score — show a dash so it
    // can't be misread as a "0 = perfect" result.
    let score = if report.risk_score.level == RiskLevel::Unknown {
        "—".to_string()
    } else {
        report.risk_score.value.to_string()
    };

    let _ = write!(
        buf,
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n\
         <meta charset=\"UTF-8\">\n\
         <title>RonwayScanner — {domain}</title>\n\
         <style>{css}</style>\n\
         </head>\n<body>\n",
        domain = esc(&report.target.domain),
        css = embedded_css(),
    );

    // Header / risk badge
    let _ = write!(
        buf,
        "<header class=\"banner\">\n\
           <h1>RonwayScanner</h1>\n\
           <p class=\"tagline\">Know your quantum risk before it knows you.</p>\n\
         </header>\n\
         <section class=\"summary\">\n\
           <div class=\"target\">\n\
             <h2>{domain}<span class=\"port\">:{port}</span></h2>\n\
             <p class=\"meta\">Scanned at {scanned_at} &middot; {duration} ms</p>\n\
           </div>\n\
           <div class=\"score\" style=\"background:{color}\">\n\
             <div class=\"score-value\">{score}</div>\n\
             <div class=\"score-level\">{level}</div>\n\
           </div>\n\
         </section>\n",
        domain = esc(&report.target.domain),
        port = report.target.port,
        scanned_at = esc(&report.target.scanned_at),
        duration = report.target.scan_duration_ms,
        color = color,
        score = score,
        level = level,
    );

    let _ = write!(
        buf,
        "<section class=\"executive\">\n<p>{summary}</p>\n",
        summary = esc(&report.summary)
    );
    if report.risk_score.harvest_risk {
        buf.push_str(
            "<p class=\"harvest\"><strong>Harvest-now-decrypt-later risk:</strong> \
             quantum-vulnerable key exchange is in use, so today's encrypted traffic \
             may be decrypted by a future quantum adversary.</p>\n",
        );
    }
    buf.push_str("</section>\n");

    write_tls_section(buf, &report.tls);
    write_cert_section(buf, &report.certificate);
    write_http_section(buf, &report.http);
    write_vulns_section(buf, &report.vulnerabilities);
    write_recommendations_section(buf, &report.recommendations);

    let _ = write!(
        buf,
        "<footer class=\"foot\">Generated by RonwayScanner v{ver} &middot; BPxAI &middot; \
         All Rights Reserved</footer>\n</body>\n</html>\n",
        ver = env!("CARGO_PKG_VERSION"),
    );
}

fn write_tls_section(buf: &mut String, tls: &Option<TlsFinding>) {
    buf.push_str("<section><h3>TLS</h3>");
    match tls {
        Some(t) => {
            let _ = write!(
                buf,
                "<table class=\"kv\">\
                 <tr><td>Protocol</td><td>{}{}</td></tr>\
                 <tr><td>Cipher suite</td><td>{}{}</td></tr>\
                 <tr><td>Key exchange</td><td>{}{}</td></tr>\
                 <tr><td>Compression</td><td>{}</td></tr>\
                 </table>",
                esc(&t.protocol_version),
                badge(t.protocol_vulnerable),
                esc(&t.cipher_suite),
                badge(t.cipher_vulnerable),
                esc(&t.key_exchange),
                badge(t.key_exchange_vulnerable),
                esc(&t.compression),
            );
        }
        None => buf.push_str("<p class=\"warn\">TLS scan failed.</p>"),
    }
    buf.push_str("</section>");
}

fn write_cert_section(buf: &mut String, cert: &Option<CertFinding>) {
    buf.push_str("<section><h3>Certificate</h3>");
    match cert {
        Some(c) => {
            let _ = write!(
                buf,
                "<table class=\"kv\">\
                 <tr><td>Subject</td><td>{}</td></tr>\
                 <tr><td>Issuer</td><td>{}</td></tr>\
                 <tr><td>Key algorithm</td><td>{}{}</td></tr>\
                 <tr><td>Signature algorithm</td><td>{}{}</td></tr>\
                 <tr><td>Valid from</td><td>{}</td></tr>\
                 <tr><td>Valid until</td><td>{}</td></tr>\
                 <tr><td>Days remaining</td><td>{}{}</td></tr>\
                 <tr><td>Self-signed</td><td>{}</td></tr>\
                 <tr><td>CT logged</td><td>{}</td></tr>\
                 </table>",
                esc(&c.subject),
                esc(&c.issuer),
                esc(&c.key_algorithm),
                badge(c.key_algorithm_vulnerable),
                esc(&c.signature_algorithm),
                badge(c.signature_algorithm_vulnerable),
                esc(&c.valid_from),
                esc(&c.valid_until),
                c.days_remaining,
                if c.is_expired {
                    " <span class=\"b-fail\">expired</span>"
                } else {
                    ""
                },
                if c.is_self_signed { "yes" } else { "no" },
                if c.ct_logged { "yes" } else { "no" },
            );
        }
        None => buf.push_str("<p class=\"warn\">Certificate scan failed.</p>"),
    }
    buf.push_str("</section>");
}

fn write_http_section(buf: &mut String, http: &Option<HttpFinding>) {
    buf.push_str("<section><h3>HTTP headers</h3>");
    match http {
        Some(h) => {
            let hsts = if h.hsts_enabled {
                match h.hsts_max_age {
                    Some(n) => format!("enabled (max-age = {} s)", n),
                    None => "enabled (no max-age)".to_string(),
                }
            } else {
                "missing".to_string()
            };
            let _ = write!(
                buf,
                "<table class=\"kv\">\
                 <tr><td>Strict-Transport-Security</td><td>{}{}</td></tr>\
                 <tr><td>Content-Security-Policy</td><td>{}</td></tr>\
                 <tr><td>X-Frame-Options</td><td>{}</td></tr>\
                 <tr><td>Server header</td><td>{}</td></tr>\
                 </table>",
                esc(&hsts),
                if !h.hsts_enabled {
                    " <span class=\"b-fail\">no HSTS</span>"
                } else {
                    ""
                },
                if h.csp_present { "present" } else { "missing" },
                opt_or_dash(&h.x_frame_options),
                opt_or_dash(&h.server_header),
            );
        }
        None => buf.push_str("<p class=\"warn\">HTTP scan failed.</p>"),
    }
    buf.push_str("</section>");
}

fn write_vulns_section(buf: &mut String, vulns: &[Vulnerability]) {
    let _ = write!(
        buf,
        "<section><h3>Vulnerabilities <span class=\"count\">({})</span></h3>",
        vulns.len()
    );
    if vulns.is_empty() {
        buf.push_str("<p>No vulnerabilities detected.</p></section>");
        return;
    }
    buf.push_str(
        "<table class=\"vulns\">\
         <thead><tr><th>Severity</th><th>ID</th><th>Title</th><th>NIST</th><th>CVSS</th></tr></thead>\
         <tbody>",
    );
    for v in vulns {
        let _ = write!(
            buf,
            "<tr>\
             <td><span class=\"sev sev-{cls}\">{level}</span></td>\
             <td><code>{id}</code></td>\
             <td>{title}<br><small>{desc}</small></td>\
             <td>{nist}</td>\
             <td>{cvss:.1}</td>\
             </tr>",
            cls = sev_class(&v.severity),
            level = v.severity.label(),
            id = esc(&v.id),
            title = esc(&v.title),
            desc = esc(&v.description),
            nist = esc(&v.nist_reference),
            cvss = v.cvss_equivalent,
        );
    }
    buf.push_str("</tbody></table></section>");
}

fn write_recommendations_section(buf: &mut String, recs: &[Recommendation]) {
    let _ = write!(
        buf,
        "<section><h3>Recommendations <span class=\"count\">({})</span></h3>",
        recs.len()
    );
    if recs.is_empty() {
        buf.push_str("<p>No remediation actions required.</p></section>");
        return;
    }
    buf.push_str(
        "<table class=\"recs\">\
         <thead><tr><th>P</th><th>Action</th><th>Current</th><th>Replace with</th>\
         <th>Effort</th><th>NIST</th></tr></thead><tbody>",
    );
    for r in recs {
        let _ = write!(
            buf,
            "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{} wk</td><td>{}</td></tr>",
            r.priority,
            esc(&r.action),
            esc(&r.current),
            esc(&r.replace_with),
            r.effort_weeks,
            esc(&r.nist_algorithm),
        );
    }
    buf.push_str("</tbody></table></section>");
}

fn sev_class(level: &RiskLevel) -> &'static str {
    match level {
        RiskLevel::Critical => "critical",
        RiskLevel::High => "high",
        RiskLevel::Medium => "medium",
        RiskLevel::Low => "low",
        RiskLevel::Pass => "pass",
        RiskLevel::Unknown => "unknown",
    }
}

fn badge(vulnerable: bool) -> &'static str {
    if vulnerable {
        " <span class=\"b-fail\">quantum-vulnerable</span>"
    } else {
        " <span class=\"b-ok\">ok</span>"
    }
}

fn opt_or_dash(s: &Option<String>) -> String {
    match s {
        Some(v) if !v.is_empty() => esc(v),
        _ => "—".to_string(),
    }
}

/// Tiny HTML-escape: enough for text in attribute values and element bodies.
fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

fn embedded_css() -> &'static str {
    r#"
:root { color-scheme: light; }
* { box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 0; color: #111; background: #f6f7fb; }
.banner { background: #0f172a; color: #fff; padding: 24px 32px; }
.banner h1 { margin: 0; font-size: 24px; letter-spacing: -0.02em; }
.banner .tagline { margin: 4px 0 0; opacity: 0.75; font-size: 14px; }
.summary { display: flex; justify-content: space-between; align-items: center; padding: 24px 32px; background: #fff; border-bottom: 1px solid #e5e7eb; }
.summary .target h2 { margin: 0; font-size: 22px; }
.summary .target .port { color: #6b7280; font-weight: 400; margin-left: 4px; }
.summary .meta { margin: 4px 0 0; color: #6b7280; font-size: 13px; }
.score { color: #fff; padding: 16px 24px; border-radius: 8px; text-align: center; min-width: 120px; }
.score-value { font-size: 36px; font-weight: 700; line-height: 1; }
.score-level { font-size: 12px; text-transform: uppercase; letter-spacing: 0.1em; margin-top: 4px; }
.executive { padding: 16px 32px; background: #fff; border-bottom: 1px solid #e5e7eb; font-size: 15px; line-height: 1.5; }
.executive .harvest { background: #fef2f2; border-left: 3px solid #dc2626; padding: 8px 12px; margin: 12px 0 0; }
section { padding: 16px 32px; }
section h3 { margin: 0 0 12px; font-size: 16px; color: #1f2937; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; }
.count { color: #6b7280; font-weight: 400; font-size: 13px; margin-left: 4px; }
table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #e5e7eb; }
table td, table th { padding: 8px 12px; text-align: left; font-size: 13px; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
table th { background: #f9fafb; font-weight: 600; color: #374151; }
.kv td:first-child { width: 240px; color: #6b7280; }
.b-ok { background: #dcfce7; color: #166534; padding: 1px 6px; border-radius: 999px; font-size: 11px; }
.b-fail { background: #fee2e2; color: #991b1b; padding: 1px 6px; border-radius: 999px; font-size: 11px; }
.sev { padding: 2px 8px; border-radius: 999px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; }
.sev-critical { background: #dc2626; color: #fff; }
.sev-high { background: #ea580c; color: #fff; }
.sev-medium { background: #ca8a04; color: #fff; }
.sev-low { background: #65a30d; color: #fff; }
.sev-pass { background: #16a34a; color: #fff; }
.sev-unknown { background: #6b7280; color: #fff; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; background: #f3f4f6; padding: 1px 6px; border-radius: 4px; font-size: 12px; }
.foot { padding: 16px 32px; color: #6b7280; font-size: 12px; text-align: center; }
.warn { color: #991b1b; }
"#
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::finding::Vulnerability;
    use crate::models::report::{ScanReport, ScanTarget};
    use crate::models::risk::{RiskLevel, RiskScore};

    fn minimal_report() -> ScanReport {
        ScanReport {
            target: ScanTarget {
                domain: "<script>alert(1)</script>".into(),
                ip_address: None,
                port: 443,
                scanned_at: "2026-05-28T00:00:00+00:00".into(),
                scan_duration_ms: 100,
            },
            risk_score: RiskScore {
                value: 35,
                level: RiskLevel::Low,
                summary: "Low risk".into(),
                harvest_risk: false,
            },
            tls: None,
            certificate: None,
            http: None,
            vulnerabilities: vec![Vulnerability {
                id: "TEST_VULN".into(),
                title: "Title & <stuff>".into(),
                description: "desc".into(),
                severity: RiskLevel::High,
                nist_reference: "FIPS 203".into(),
                cvss_equivalent: 7.4,
            }],
            recommendations: vec![],
            summary: "summary".into(),
            quantum_ready: false,
        }
    }

    #[test]
    fn html_starts_with_doctype() {
        let html = HtmlReporter::render(&minimal_report());
        assert!(html.starts_with("<!DOCTYPE html>"));
    }

    #[test]
    fn html_escapes_user_strings() {
        let html = HtmlReporter::render(&minimal_report());
        assert!(html.contains("&lt;script&gt;"));
        assert!(!html.contains("<script>alert(1)</script>"));
        assert!(html.contains("Title &amp; &lt;stuff&gt;"));
    }

    #[test]
    fn html_contains_no_external_urls() {
        let html = HtmlReporter::render(&minimal_report());
        // Self-contained requirement per CLAUDE.md.
        assert!(!html.contains("http://"));
        assert!(!html.contains("https://"));
        assert!(!html.contains("//cdn"));
    }

    #[test]
    fn html_shows_failure_messages_when_scanners_missing() {
        let html = HtmlReporter::render(&minimal_report());
        assert!(html.contains("TLS scan failed"));
        assert!(html.contains("Certificate scan failed"));
        assert!(html.contains("HTTP scan failed"));
    }
}
